---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install VSFTPD package
      yum:
        name: vsftpd
        state: latest
    - name: Install HTTPD package
      yum:
        name: httpd
        state: latest
    - name: Start and Enable VSFTPD service
      service:
        name: vsftpd
        state: started
        enabled: true

    - name: Start and Enable HTTPD service
      service:
        name: httpd
        state: started
        enabled: true
